# -*- coding: utf-8 -*-
"""
지적측량규칙 2021 (뉴질랜드) 의 제목 대역.

RULE  : 규칙 번호 → 한국어 제목
HEAD  : 편·절·별표 제목 → 한국어 제목

우리 작업규정의 말로 옮겼다. parcel 은 '필지', primary/non-primary parcel 은
'주(主) 필지 / 부(副) 필지', class A~D 는 'A~D급', CSD(cadastral survey
dataset) 는 '지적측량 성과묶음' 으로 통일하였다.
"""

RULE = {
    "1": "제목", "2": "시행일",
    "3": "이 규칙의 목적",
    "4": "경과조치 및 관련 규정",
    "5": "용어의 정의(별표 2)",
    "6": "측량으로 경계를 정할 때 측량사의 의무",
    "7": "직선 경계", "8": "호(원호) 경계", "9": "부정형 경계",
    "10": "수변 경계", "11": "수로 중심선 경계", "12": "높이 한정 경계",
    "13": "측량으로 정하여야 하는 경계와 경계점",
    "14": "원용할 수 있는 자료", "15": "경계의 인정",
    "16": "수평기준: 방위 결정", "17": "수평기준: 연결", "18": "수직기준",
    "19": "경계표지 외 표지의 정확도",
    "20": "기준점망 연결의 정확도",
    "21": "경계 참조측량의 정확도",
    "22": "A급의 적용", "23": "B급의 적용", "24": "C급의 적용", "25": "D급의 적용",
    "26": "이어진 경계의 등급이 서로 다른 경우 적용 등급",
    "27": "경계점의 정확도",
    "28": "겹침을 막을 수 있는 정확도",
    "29": "수변·수로 중심선·부정형 경계의 정확도",
    "30": "직선 경계와 수변·수로 중심선·부정형 경계가 만나는 점의 정확도",
    "31": "경계점의 참조측량 의무",
    "32": "영구 참조표지의 개수와 거리",
    "33": "영구 참조표지의 재질과 형태",
    "34": "높이 한정 경계 참조표지의 표고 성과",
    "35": "경계표지 설치 의무", "36": "새 경계표지",
    "37": "흔들리거나 훼손된 경계표지와 측량표지",
    "38": "주(主) 필지의 경계",
    "39": "주 필지의 빠짐없는 처리", "40": "필지의 너비", "41": "필지의 면적",
    "42": "일반 토지의 지번 표기", "43": "필지 종류 표기 요소",
    "44": "마오리 토지의 지번 표기", "45": "필지 고유번호",
    "46": "부(副) 필지의 경계",
    "47": "경계를 가로지르는 부 필지",
    "48": "지역권 일부 포기 또는 약정 일부 해지",
    "49": "중심선 지역권",
    "50": "부 필지의 A급·B급",
    "51": "기초 필지와의 관계가 부정확한 A급·B급",
    "52": "부 필지의 C급",
    "53": "기초 필지와의 관계가 부정확한 C급",
    "54": "부 필지 경계의 인정",
    "55": "기초 필지가 측량으로 만들어지지 않은 경우의 정확도와 측량 기준",
    "56": "영구 구조물 경계", "57": "영구 구조물 경계의 정확도",
    "58": "기존 구분소유·임차 경계의 인정",
    "59": "구분소유 개발의 성과묶음 번호",
    "60": "수직기준과 수직 기준점",
    "61": "높이 한정 경계점의 참조측량",
    "62": "기존 구분소유 개발의 높이 한정 경계점",
    "63": "부 필지의 경계표지",
    "64": "부 필지에 표지를 설치한 경우의 참조표지",
    "65": "적용범위", "66": "공유 해면·연안구역의 C급",
    "67": "기존 수변 경계의 인정",
    "68": "대조평균고조면(MHWS)·대조평균저조면(MLWS)의 이격",
    "69": "만나는 경계의 등급과 치수", "70": "수평기준과 연결",
    "71": "성과묶음의 구성", "72": "측량보고서에 담을 사항",
    "73": "측량사의 인증", "74": "성과묶음의 단위",
    "75": "원용한 자료와 원자료의 일치",
    "76": "측량 기록", "77": "기준계 정보", "78": "벡터(방위·거리) 정보",
    "79": "경계 정보", "80": "측량표지 정보",
    "81": "점유 상태와 지물 정보",
    "82": "측량표지 정보의 표시", "83": "필지 정보",
    "84": "가동 연안 완충대의 필지 정보",
    "85": "수변·수로 중심선·부정형 경계", "86": "높이 한정 경계",
    "87": "필지 주기", "88": "경계 주기", "89": "벡터",
    "90": "도면 기호·선종·문자", "91": "측량 도면의 표현 방법",
    "92": "권리도 정보", "93": "새 지역권 정보", "94": "기존 지역권 정보",
    "95": "약정 정보", "96": "면적 조서",
    "97": "필지 정보", "98": "구분소유·교차임차 개발의 필지 정보",
    "99": "가동 연안 완충대의 필지 정보",
    "100": "수변·수로 중심선·부정형 경계", "101": "영구 구조물 경계",
    "102": "높이 한정 경계", "103": "필지 주기", "104": "경계 주기",
    "105": "경계 치수", "106": "도면 기호·선종·문자",
    "107": "권리 도면의 표현 방법",
    "108": "용어의 뜻",
    "109": "지반 변동으로 영향받은 경계의 복원",
    "110": "부 필지 경계의 결정",
    "111": "광역 크라이스트처치의 기초 필지 경계 재결정",
    "112": "용어의 뜻",
    "113": "경계표지 설치 시 성과묶음 제출 의무",
    "114": "복합 경계 복원과 그 제한",
    "115": "수평기준: 방위 결정", "116": "참조표지",
    "117": "단순 경계 복원 성과묶음의 구성",
    "118": "측량보고서", "119": "측량 기록", "120": "복원 도면",
    "121": "도면 기호·선종·문자",
    "122": "폐지",
}

HEAD = {
    "Rules": "규칙",
    "Part 1 Preliminary provisions": "제1편 총칙",
    "Part 2 Duty of surveyor": "제2편 측량사의 의무",
    "Part 3 Boundaries": "제3편 경계",
    "Part 4 Field survey": "제4편 현지측량",
    "Part 5 Parcels": "제5편 필지",
    "Part 6 Non-primary parcels": "제6편 부(副) 필지",
    "Part 7 Cadastral survey datasets": "제7편 지적측량 성과묶음",
    "Part 8 Ground movement": "제8편 지반 변동",
    "Part 9 Boundary reinstatements": "제9편 경계 복원",
    "Part 10 Revocation": "제10편 폐지",

    "Subpart 1 —Form of boundaries": "제1절 경계의 형태",
    "Subpart 1 —Form of boundary": "제1절 경계의 형태",
    "Subpart 2 —Quality of boundary definition": "제2절 경계 결정의 품질",
    "Subpart 1 —Datum": "제1절 기준계",
    "Subpart 2 —Accuracy standards": "제2절 정확도 기준",
    "Subpart 3 —Accuracy standards": "제3절 정확도 기준",
    "Subpart 3 —Reference marks": "제3절 참조표지",
    "Subpart 4 —Boundary marking": "제4절 경계표지 설치",
    "Subpart 2 —Parcel extents": "제2절 필지의 범위",
    "Subpart 3 —Parcel appellation": "제3절 필지의 표기",
    "Subpart 2 —Parcels": "제2절 필지",
    "Subpart 4 —Permanent structure boundaries": "제4절 영구 구조물 경계",
    "Subpart 5 —Existing unit and lease developments": "제5절 기존 구분소유·임차 개발",
    "Subpart 6 —Height-limited boundaries": "제6절 높이 한정 경계",
    "Subpart 7 —Non-primary parcel marking and reference marks":
        "제7절 부 필지의 표지와 참조표지",
    "Subpart 8 —Non-primary parcels over water": "제8절 수면 위의 부 필지",
    "Subpart 1 —Generic CSD requirements": "제1절 성과묶음 공통 기준",
    "Subpart 2 —Record of survey": "제2절 측량 기록",
    "Subpart 3 —Survey diagram": "제3절 측량 도면",
    "Subpart 4 —Title plan": "제4절 권리도",
    "Subpart 5 —Title diagram": "제5절 권리 도면",
    "Subpart 1 —Preliminary provisions": "제1절 총칙",
    "Subpart 2 —Parcel boundaries subject to ground movement":
        "제2절 지반 변동을 받은 필지 경계",
    "Subpart 2 —General requirements": "제2절 일반 기준",
    "Subpart 3 —Complex boundary reinstatements": "제3절 복합 경계 복원",
    "Subpart 4 —Simple boundary reinstatements: field survey":
        "제4절 단순 경계 복원 — 현지측량",
    "Subpart 5 —Simple boundary reinstatement CSD":
        "제5절 단순 경계 복원 성과묶음",

    "Schedule 1 Transitional, savings, and related provisions":
        "별표 1 경과조치 및 관련 규정",
    "Schedule 2 Dictionary": "별표 2 용어사전",
    "Schedule 3 Official geodetic datum and projections":
        "별표 3 공식 측지기준계와 투영법",
    "Schedule 4 Cadastral survey network marks": "별표 4 지적측량 기준점망 표지",
    "Schedule 5 Official vertical datum": "별표 5 공식 수직기준",
    "Schedule 6 Vertical control marks": "별표 6 수직 기준점 표지",
    "Schedule 7 Diagram symbols, line styles, and text":
        "별표 7 도면 기호·선종·문자",
}

# 별표 1·7 안의 조항 제목
CLAUSE = {
    "Existing surveys may be completed under Rules for Cadastral Survey 2010":
        "이미 시작한 측량은 2010년 규칙에 따라 마칠 수 있다",
    "Symbol and text depiction": "기호와 문자의 표시",
    "Symbols": "기호",
    "Line styles": "선의 종류",
    "Font size for text": "문자의 크기",
    "NZVD2016": "뉴질랜드 수직기준 2016 (NZVD2016)",
}


# 별표 2 사전의 낱말 대역
TERM = {
    "accepted": "인정된",
    "Act": "법(지적측량법 2002)",
    "adopt": "원용하다",
    "affected boundary": "영향받은 경계",
    "approved CSD": "승인된 성과묶음",
    "balance parcel": "잔여 필지",
    "boundary mark": "경계표지",
    "boundary point": "경계점",
    "cadastral survey dataset": "지적측량 성과묶음",
    "cadastral survey network mark": "지적측량 기준점망 표지",
    "cadastre": "지적(地籍)",
    "Canterbury earthquake movement": "캔터베리 지진에 따른 지반 변동",
    "centre-line easement": "중심선 지역권",
    "chief executive": "청장(소관 기관의 장)",
    "common marine and coastal area": "공유 해면·연안구역",
    "company lease": "법인 임차",
    "conflict": "충돌(경계의 어긋남)",
    "cross lease": "교차임차",
    "CSD": "성과묶음(CSD)",
    "CSD number": "성과묶음 번호",
    "deposited": "등록된",
    "disturbed survey mark": "흔들리거나 옮겨진 측량표지",
    "esplanade strip": "해안 산책 완충대",
    "estate boundary": "권리 경계",
    "extinguished": "소멸된",
    "fault zone movement": "단층대 변동",
    "fixed marginal strip": "고정 연안 완충대",
    "Hawke’s Bay interim title": "호크스베이 임시 권리증",
    "inaccurately determined": "부정확하게 정해진",
    "Māori customary land": "마오리 관습지",
    "Māori freehold land": "마오리 자유보유지",
    "marginal strip": "연안 완충대",
    "MHWS": "대조평균고조면(MHWS)",
    "MLWS": "대조평균저조면(MLWS)",
    "movable marginal strip": "가동 연안 완충대",
    "non-boundary mark": "경계표지 외의 표지",
    "non-primary parcel": "부(副) 필지",
    "official projection": "공식 투영법",
    "old survey mark": "옛 측량표지",
    "parcel": "필지",
    "parcel intent": "필지의 용도 구분",
    "permanent reference mark": "영구 참조표지",
    "PRM": "영구 참조표지(PRM)",
    "permanent structure boundary": "영구 구조물 경계",
    "primary parcel": "주(主) 필지",
    "reinstated": "복원된",
    "renewed": "다시 설치된",
    "residue parcel": "나머지 필지",
    "survey mark": "측량표지",
    "underlying parcel": "기초 필지",
    "vector": "벡터(방위와 거리)",
    "vertical control mark": "수직 기준점 표지",
}
